In [0]:
import numpy as np
import pandas as pd
# from numpy.linalg import svd
from sklearn.decomposition import TruncatedSVD

In [0]:
# A = np.array([[1,2,3],[2,3,4]])
# A

In [0]:
# U,S,VT = svd(A)

In [0]:
# print(VT)

In [48]:
from google.colab import files
uploads = files.upload()

Saving Nairobi Office Price Ex.csv to Nairobi Office Price Ex (2).csv


In [49]:
data = pd.read_csv('Nairobi Office Price Ex.csv')
data.tail()

LOC  FUR          AMB PROX_SCH  ... WATER HK_SER       SIZE      PRICE
9      karen  yes       serene       no  ...    no     no  52.550014  71.300880
10  madaraka  yes        noisy      yes  ...   yes    yes  45.419730  55.165677
11   langata   no  semi_serene      yes  ...   yes    yes  54.351635  82.478847
12  buruburu  yes  semi_serene      yes  ...    no     no  44.164049  62.008923
13     karen  yes  semi_serene      yes  ...   yes    yes  58.168471  75.392870

[5 rows x 10 columns]

In [50]:
nominal=['LOC','FUR','WATER','HK_SER']
ordinal=['AMB','PROX_SCH','PROX_ROAD','PROX_MALL']
numerical = ['SIZE']
target = ['PRICE']
categorical_data = data.select_dtypes(include=['object']).copy()
categorical_cols = list(categorical_data.columns)

for col in categorical_cols:
  categorical_data[col] = categorical_data[col].astype('category')

for feature in ordinal:
  categorical_data[feature] = categorical_data[feature].cat.codes

categorical_data.head()

LOC  FUR  AMB  PROX_SCH  PROX_ROAD  PROX_MALL WATER HK_SER
0     karen  yes    2         0          1          1   yes    yes
1  madaraka  yes    1         1          1          1    no     no
2     karen   no    0         0          1          1   yes    yes
3     karen  yes    1         0          0          0   yes    yes
4  buruburu   no    1         0          1          1   yes    yes

In [51]:
# OH Encoding using pandas
data_copy = categorical_data.copy()
data_copy = pd.concat([pd.get_dummies(data_copy[nominal]),data_copy],axis=1) 
data_copy.drop(nominal,axis=1,inplace=True)
data_copy.head()

LOC_buruburu  LOC_donholm  LOC_karen  ...  PROX_SCH  PROX_ROAD  PROX_MALL
0             0            0          1  ...         0          1          1
1             0            0          0  ...         1          1          1
2             0            0          1  ...         0          1          1
3             0            0          1  ...         0          0          0
4             1            0          0  ...         0          1          1

[5 rows x 15 columns]

In [52]:
new_data = pd.concat([data_copy, data[numerical], data[target]], axis=1)
new_data.head()

LOC_buruburu  LOC_donholm  LOC_karen  ...  PROX_MALL       SIZE      PRICE
0             0            0          1  ...          1  32.502345  31.707006
1             0            0          0  ...          1  53.426804  68.777596
2             0            0          1  ...          1  61.530358  62.562382
3             0            0          1  ...          0  47.475640  71.546632
4             1            0          0  ...          1  59.813208  87.230925

[5 rows x 17 columns]

In [53]:
X = new_data.drop("PRICE", 1)
data_array = X.to_numpy()
data_array

array([[ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  2.        ,  0.        ,  1.        ,  1.        ,
        32.50234527],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ,  1.        ,  0.        ,  1.        ,
         0.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        53.42680403],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  1.        ,
        61.53035803],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
        47.47563963],
       [ 1.        ,  0.        ,  0

In [54]:
Tsvd = TruncatedSVD(n_components=2)
data_approx = Tsvd.fit_transform(data_array)
data_approx

array([[32.59067248, -0.31296456],
       [53.46778496, -0.51284032],
       [61.5425652 ,  1.84399183],
       [47.50479939,  0.43325415],
       [59.84701785,  0.98922952],
       [55.18765095, -0.66580331],
       [52.29472771, -1.58958668],
       [39.36187158, -1.08471401],
       [48.13307416, -0.2865976 ],
       [52.58778358, -1.40400383],
       [45.44308725,  1.16566524],
       [54.38965254,  0.58800498],
       [44.20133601, -0.79910776],
       [58.22132174,  0.7714815 ]])

In [55]:
Tsvd.singular_values_

array([190.59287448,   3.75044979])

In [0]:
# final_data = pd.concat([data_approx, data[target]],axis=1)
# final_data