In [0]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LassoCV
import seaborn as sns
import matplotlib.pyplot as plt

In [175]:
from google.colab import files
uploads = files.upload()

Saving train_data.csv to train_data (4).csv


### Load the dataset

In [176]:
# load the dataset using pandas
house_data = pd.read_csv('train_data (4).csv')
house_data.head()

Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

### Understanding the dataset

In [177]:
# check no. of rows and columns in the dataset
house_data.shape

(1460, 81)

In [178]:
# check column types
house_data.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...   
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

In [179]:
# check count of column types
house_data.dtypes.value_counts()

object     43
int64      35
float64     3
dtype: int64

In [180]:
# check number of null values in each column
house_data.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [181]:
# list all columns in the dataset
print(house_data.columns)
print("\n No. of columns:", house_data.columns.size)

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

### Divide dataset into target and predictive features

In [182]:
# get target and predictive features 
y = house_data['SalePrice']
X = house_data.drop('SalePrice', 1)
X.head()

Id  MSSubClass MSZoning  LotFrontage  ...  MoSold YrSold SaleType SaleCondition
0   1          60       RL         65.0  ...       2   2008       WD        Normal
1   2          20       RL         80.0  ...       5   2007       WD        Normal
2   3          60       RL         68.0  ...       9   2008       WD        Normal
3   4          70       RL         60.0  ...       2   2006       WD       Abnorml
4   5          60       RL         84.0  ...      12   2008       WD        Normal

[5 rows x 80 columns]

### Check for nulls in the Target

In [183]:
# check type of the target feature and availability of null values
print(y.dtype)
y.isnull().any()

int64


False

### Check for Nulls in Predictive features


In [184]:
for col in X.columns:
  if X[col].isna().any():
    print(col, X[col].isna().sum())

LotFrontage 259
Alley 1369
MasVnrType 8
MasVnrArea 8
BsmtQual 37
BsmtCond 37
BsmtExposure 38
BsmtFinType1 37
BsmtFinType2 38
Electrical 1
FireplaceQu 690
GarageType 81
GarageYrBlt 81
GarageFinish 81
GarageQual 81
GarageCond 81
PoolQC 1453
Fence 1179
MiscFeature 1406


### Deal with Nulls in Predictive features

In [185]:
# get numerical columns form X
numerical_cols = [col for col in X.columns
                  if X[col].dtype == 'int64' or X[col].dtype == 'float64']
print("List of Numerical Columns \n", numerical_cols)
print("No. of Numerical Columns:", len(numerical_cols))

# get object columns form X
object_cols = [col for col in X.columns
                    if X[col].dtype == 'object']
print("\nList of Object Columns \n", object_cols)
print("No. of Object Columns:", len(object_cols)) 

List of Numerical Columns 
 ['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold']
No. of Numerical Columns: 37

List of Object Columns 
 ['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQ

In [186]:
# replace null values in numerical columns with the mean
imputer = SimpleImputer(strategy = 'median')
imputed_num = pd.DataFrame(imputer.fit_transform(X[numerical_cols]))
# return column names removed due to imputation
imputed_num.columns = list(X[numerical_cols].columns)
imputed_num.head()

Id  MSSubClass  LotFrontage  LotArea  ...  PoolArea  MiscVal  MoSold  YrSold
0  1.0        60.0         65.0   8450.0  ...       0.0      0.0     2.0  2008.0
1  2.0        20.0         80.0   9600.0  ...       0.0      0.0     5.0  2007.0
2  3.0        60.0         68.0  11250.0  ...       0.0      0.0     9.0  2008.0
3  4.0        70.0         60.0   9550.0  ...       0.0      0.0     2.0  2006.0
4  5.0        60.0         84.0  14260.0  ...       0.0      0.0    12.0  2008.0

[5 rows x 37 columns]

In [187]:
# replace null values in object columns with the most frequent value
imputer = SimpleImputer(strategy = 'most_frequent')
imputed_obj = pd.DataFrame(imputer.fit_transform(X[object_cols]))
# return column names removed due to imputation
imputed_obj.columns = list(X[object_cols].columns)
imputed_obj.head()

MSZoning Street Alley LotShape  ...  Fence MiscFeature SaleType SaleCondition
0       RL   Pave  Grvl      Reg  ...  MnPrv        Shed       WD        Normal
1       RL   Pave  Grvl      Reg  ...  MnPrv        Shed       WD        Normal
2       RL   Pave  Grvl      IR1  ...  MnPrv        Shed       WD        Normal
3       RL   Pave  Grvl      IR1  ...  MnPrv        Shed       WD       Abnorml
4       RL   Pave  Grvl      IR1  ...  MnPrv        Shed       WD        Normal

[5 rows x 43 columns]

In [188]:
# combine imputed numerical and object columns
imputed_X = pd.concat([imputed_num,imputed_obj],axis=1)
imputed_X.head()

Id  MSSubClass  LotFrontage  ...  MiscFeature  SaleType  SaleCondition
0  1.0        60.0         65.0  ...         Shed        WD         Normal
1  2.0        20.0         80.0  ...         Shed        WD         Normal
2  3.0        60.0         68.0  ...         Shed        WD         Normal
3  4.0        70.0         60.0  ...         Shed        WD        Abnorml
4  5.0        60.0         84.0  ...         Shed        WD         Normal

[5 rows x 80 columns]

In [189]:
imputed_X.shape

(1460, 80)

### Encode categorical predictive features 

In [0]:
# categorize predictive features as either numerical, nominal or ordinal
numerical = numerical_cols # 37 columns
nominal = ['Neighborhood', 'CentralAir', 'Electrical', 'MiscFeature', 'RoofStyle', 'RoofMatl', 
           'Exterior1st', 'Exterior2nd', 'MasVnrType', 'Foundation', 'GarageType', 'SaleType', 'Heating', 'SaleCondition'] # 14 features
ordinal = ['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig','LandSlope', 'Condition1', 
           'Condition2','BldgType', 'HouseStyle', 'ExterQual', 'ExterCond', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 
           'BsmtFinType1', 'BsmtFinType2', 'HeatingQC', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageQual', 
           'GarageFinish', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence'] # 29 features
target = ['SalePrice'] # 1 column

In [192]:
# obtain categorical data
categorical_data = imputed_X.select_dtypes(include=['object']).copy()
categorical_cols = list(categorical_data.columns)

for col in categorical_cols:
  categorical_data[col] = categorical_data[col].astype('category')

# Label encode ordinal predictive features 
for feature in ordinal:
  value = categorical_data[feature]
  encoder = LabelEncoder()
  trans_f = encoder.fit_transform(value)
  categorical_data[feature] = trans_f

categorical_data.head()

MSZoning  Street  Alley  LotShape  ...  Fence  MiscFeature  SaleType  SaleCondition
0         3       1      0         3  ...      2         Shed        WD         Normal
1         3       1      0         3  ...      2         Shed        WD         Normal
2         3       1      0         0  ...      2         Shed        WD         Normal
3         3       1      0         0  ...      2         Shed        WD        Abnorml
4         3       1      0         0  ...      2         Shed        WD         Normal

[5 rows x 43 columns]

In [193]:
# OH Encode nominal predictive features
encoded_categorical_data = categorical_data.copy()
encoded_categorical_data = pd.concat([pd.get_dummies(encoded_categorical_data[nominal]),encoded_categorical_data],axis=1) 
encoded_categorical_data.drop(nominal,axis=1,inplace=True)
encoded_categorical_data.head()

Neighborhood_Blmngtn  Neighborhood_Blueste  ...  PoolQC  Fence
0                     0                     0  ...       2      2
1                     0                     0  ...       2      2
2                     0                     0  ...       2      2
3                     0                     0  ...       2      2
4                     0                     0  ...       2      2

[5 rows x 147 columns]

In [194]:
# get dataset that includes numerical features and encoded categorical features
X_prepared = pd.concat([encoded_categorical_data, imputed_X[numerical]], axis=1)
X_prepared.head()

Neighborhood_Blmngtn  Neighborhood_Blueste  ...  MoSold  YrSold
0                     0                     0  ...     2.0  2008.0
1                     0                     0  ...     5.0  2007.0
2                     0                     0  ...     9.0  2008.0
3                     0                     0  ...     2.0  2006.0
4                     0                     0  ...    12.0  2008.0

[5 rows x 184 columns]

In [195]:
X_prepared.shape

(1460, 184)

### Form a Matrix from already prepared Predictive Features

In [201]:
# convert prepared X to an array
X_array = X_prepared.to_numpy()
X_array

array([[0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 2.000e+00,
        2.008e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 5.000e+00,
        2.007e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 9.000e+00,
        2.008e+03],
       ...,
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 2.500e+03, 5.000e+00,
        2.010e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 4.000e+00,
        2.010e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 6.000e+00,
        2.008e+03]])

In [197]:
# standardize the array of prepare X using StandardScaler
X_standardized = StandardScaler().fit_transform(X_array)
X_standardized

array([[-0.10854037, -0.03703704, -0.10526316, ..., -0.08768781,
        -1.5991111 ,  0.13877749],
       [-0.10854037, -0.03703704, -0.10526316, ..., -0.08768781,
        -0.48911005, -0.61443862],
       [-0.10854037, -0.03703704, -0.10526316, ..., -0.08768781,
         0.99089135,  0.13877749],
       ...,
       [-0.10854037, -0.03703704, -0.10526316, ...,  4.95311151,
        -0.48911005,  1.64520971],
       [-0.10854037, -0.03703704, -0.10526316, ..., -0.08768781,
        -0.8591104 ,  1.64520971],
       [-0.10854037, -0.03703704, -0.10526316, ..., -0.08768781,
        -0.1191097 ,  0.13877749]])

### Perform PCA and filter out 2 Principal Components (PC)

In [198]:
pca = PCA(n_components=2)
pc_s = pca.fit_transform(X_standardized)
pca_data = pd.DataFrame(pc_s, columns=['PC1', 'PC2'])
final_data = pd.concat([pca_data, house_data[target]], axis=1)
final_data.head()

PC1       PC2  SalePrice
0  3.108287 -0.768565     208500
1 -0.601471  2.627568     181500
2  3.500740 -0.261946     223500
3 -2.171968 -1.457954     140000
4  5.382802  0.406062     250000

Determine the percentage of information carried by the above 2 Principal Components 

In [199]:
pca.explained_variance_ratio_

array([0.07664146, 0.0333867 ])

If we were to capture 90% variance, how many PCs will be needed?

In [202]:
pca = PCA(0.9)
pca.fit_transform(X_standardized)
pca.n_components_

106