In [5]:
from torch import nn
import torch
from torch import tensor

In [6]:
x_data = tensor([[1.0], [2.0], [3.0]])
y_data = tensor([[2.0], [4.0], [6.0]])

In [7]:
x_data.shape

torch.Size([3, 1])

In [8]:
y_data.shape

torch.Size([3, 1])

In [16]:
class Model(nn.Module):
    def __init__(self):
        """
        In the constructor we instantiate two nn.Linear module
        """
        super(Model, self).__init__()
        self.linear = torch.nn.Linear(1, 1)  # One in and one out

    def forward(self, x):
        """
        In the forward function we accept a Variable of input data and we must return
        a Variable of output data. We can use Modules defined in the constructor as
        well as arbitrary operators on Variables.
        """
        y_pred = self.linear(x)
        return y_pred


In [17]:
# model
model = Model()

In [20]:
model(x_data)

tensor([[-0.0564],
        [-0.9889],
        [-1.9213]], grad_fn=<AddmmBackward>)

In [18]:
for p in model.parameters():
    print(p.shape,p.data)

torch.Size([1, 1]) tensor([[-0.9324]])
torch.Size([1]) tensor([0.8760])


In [19]:
# Construct our loss function and an Optimizer. The call to model.parameters()
# in the SGD constructor will contain the learnable parameters of the two
# nn.Linear modules which are members of the model.
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [13]:
# Training loop
for epoch in range(500):
    # 1) Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x_data)

    # 2) Compute and print loss
    loss = criterion(y_pred, y_data)
    print(f'Epoch: {epoch} | Loss: {loss.item()} ')

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

Epoch: 0 | Loss: 29.709991455078125 
Epoch: 1 | Loss: 13.290584564208984 
Epoch: 2 | Loss: 5.980203151702881 
Epoch: 3 | Loss: 2.72491455078125 
Epoch: 4 | Loss: 1.2748510837554932 
Epoch: 5 | Loss: 0.6284360289573669 
Epoch: 6 | Loss: 0.33979493379592896 
Epoch: 7 | Loss: 0.2104371190071106 
Epoch: 8 | Loss: 0.1520005166530609 
Epoch: 9 | Loss: 0.12514783442020416 
Epoch: 10 | Loss: 0.1123678907752037 
Epoch: 11 | Loss: 0.1058642566204071 
Epoch: 12 | Loss: 0.10216652601957321 
Epoch: 13 | Loss: 0.09972938895225525 
Epoch: 14 | Loss: 0.09786485135555267 
Epoch: 15 | Loss: 0.09626659750938416 
Epoch: 16 | Loss: 0.09479750692844391 
Epoch: 17 | Loss: 0.09339704364538193 
Epoch: 18 | Loss: 0.09203792363405228 
Epoch: 19 | Loss: 0.09070750325918198 
Epoch: 20 | Loss: 0.08940065652132034 
Epoch: 21 | Loss: 0.08811423182487488 
Epoch: 22 | Loss: 0.08684715628623962 
Epoch: 23 | Loss: 0.0855989009141922 
Epoch: 24 | Loss: 0.08436865359544754 
Epoch: 25 | Loss: 0.08315599709749222 
Epoch: 26 

Epoch: 233 | Loss: 0.004094916861504316 
Epoch: 234 | Loss: 0.004036046098917723 
Epoch: 235 | Loss: 0.003978070802986622 
Epoch: 236 | Loss: 0.003920861054211855 
Epoch: 237 | Loss: 0.003864553291350603 
Epoch: 238 | Loss: 0.0038090047892183065 
Epoch: 239 | Loss: 0.0037542572245001793 
Epoch: 240 | Loss: 0.003700309433043003 
Epoch: 241 | Loss: 0.0036471099592745304 
Epoch: 242 | Loss: 0.003594717476516962 
Epoch: 243 | Loss: 0.0035430295392870903 
Epoch: 244 | Loss: 0.0034920903854072094 
Epoch: 245 | Loss: 0.0034419463481754065 
Epoch: 246 | Loss: 0.003392463084310293 
Epoch: 247 | Loss: 0.0033437246456742287 
Epoch: 248 | Loss: 0.0032956362701952457 
Epoch: 249 | Loss: 0.0032482901588082314 
Epoch: 250 | Loss: 0.003201605984941125 
Epoch: 251 | Loss: 0.003155576530843973 
Epoch: 252 | Loss: 0.003110240213572979 
Epoch: 253 | Loss: 0.0030655215959995985 
Epoch: 254 | Loss: 0.00302149448543787 
Epoch: 255 | Loss: 0.002978065051138401 
Epoch: 256 | Loss: 0.0029352493584156036 
Epoch:

Epoch: 442 | Loss: 0.00019875145517289639 
Epoch: 443 | Loss: 0.00019589514704421163 
Epoch: 444 | Loss: 0.00019307727052364498 
Epoch: 445 | Loss: 0.00019030469411518425 
Epoch: 446 | Loss: 0.00018756809004116803 
Epoch: 447 | Loss: 0.00018487263878341764 
Epoch: 448 | Loss: 0.00018221710342913866 
Epoch: 449 | Loss: 0.0001795994903659448 
Epoch: 450 | Loss: 0.0001770162780303508 
Epoch: 451 | Loss: 0.00017447560094296932 
Epoch: 452 | Loss: 0.00017196623957715929 
Epoch: 453 | Loss: 0.00016949549899436533 
Epoch: 454 | Loss: 0.000167060672538355 
Epoch: 455 | Loss: 0.00016465986846014857 
Epoch: 456 | Loss: 0.00016228831373155117 
Epoch: 457 | Loss: 0.00015995599096640944 
Epoch: 458 | Loss: 0.00015766246360726655 
Epoch: 459 | Loss: 0.0001553949259687215 
Epoch: 460 | Loss: 0.00015315963537432253 
Epoch: 461 | Loss: 0.00015095841081347317 
Epoch: 462 | Loss: 0.00014878800720907748 
Epoch: 463 | Loss: 0.0001466488029109314 
Epoch: 464 | Loss: 0.00014454606571234763 
Epoch: 465 | Loss

In [14]:
# After training
hour_var = tensor([[4.0]])
y_pred = model(hour_var)
print("Prediction (after training)",  4, model(hour_var).data[0][0].item())

Prediction (after training) 4 7.989271640777588


In [15]:
list(model.parameters())

[Parameter containing:
 tensor([[1.9938]], requires_grad=True),
 Parameter containing:
 tensor([0.0141], requires_grad=True)]