
What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [1]:
import torch
import numpy as np

<div class="alert alert-info"><h4>Note</h4><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>



Construct a 5x3 matrix, uninitialized:



In [20]:
x = torch.empty(5, 3)
print(x)

tensor([[1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39],
        [1.0653e-38, 1.0469e-38, 4.2246e-39],
        [1.0378e-38, 9.6429e-39, 9.2755e-39]])


Construct a randomly initialized matrix:



In [21]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3390, 0.1685, 0.9454],
        [0.4407, 0.2726, 0.3800],
        [0.2047, 0.7220, 0.3646],
        [0.7110, 0.9270, 0.8676],
        [0.1317, 0.4857, 0.6318]])


Construct a matrix filled zeros and of dtype long:



In [22]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [23]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [24]:
x.shape

torch.Size([2])

or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [33]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)                                   # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [34]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)  

tensor([[-5.1098e-01,  1.9101e+00, -5.3828e-01],
        [ 2.8741e-01, -2.0482e-01,  2.9420e-01],
        [-7.7881e-01,  1.0883e+00,  8.9995e-01],
        [ 1.7086e+00, -1.2016e+00,  3.1006e-04],
        [-9.1062e-02, -5.4713e-01, -1.6330e+00]])


Get its size:



In [35]:
print(x.size())

torch.Size([5, 3])


# Arithmetic Ops

In [36]:
x1 = torch.ones(3,3)
x2 = torch.ones_like(x1)

In [37]:
x1+x2

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


Addition: syntax 1



In [2]:
y = torch.randint(1,4, (2,2))
x = torch.randint(1,4,(2,2))

In [3]:
y

tensor([[3, 1],
        [2, 3]])

In [4]:
x

tensor([[2, 2],
        [3, 2]])

In [5]:
print(x+y)

tensor([[5, 3],
        [5, 5]])


In [6]:
print(x-y)

tensor([[-1,  1],
        [ 1, -1]])


In [7]:
print(x.matmul(y))

tensor([[10,  8],
        [13,  9]])


In [8]:
print(torch.add(x, y))

tensor([[5, 3],
        [5, 5]])


Addition: providing an output tensor as argument



In [9]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[5., 3.],
        [5., 5.]])


Addition: in-place



In [10]:
# adds x to y
y.add_(x)
print(y)

tensor([[5, 3],
        [5, 5]])


In [11]:
y

tensor([[5, 3],
        [5, 5]])

<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



# Slicing

In [13]:
temp = torch.rand(4,4)

In [14]:
temp

tensor([[0.9133, 0.0958, 0.8372, 0.5992],
        [0.4477, 0.2830, 0.3671, 0.7826],
        [0.4283, 0.0112, 0.8482, 0.6084],
        [0.3286, 0.2693, 0.3833, 0.3434]])

In [15]:
temp[0]

tensor([0.9133, 0.0958, 0.8372, 0.5992])

In [16]:
temp[-1]

tensor([0.3286, 0.2693, 0.3833, 0.3434])

In [17]:
temp[1,1]

tensor(0.2830)

In [18]:
X, y = temp[:,:-1],temp[:,-1:],

In [19]:
y

tensor([[0.5992],
        [0.7826],
        [0.6084],
        [0.3434]])

In [20]:
temp[0:1,1:]

tensor([[0.0958, 0.8372, 0.5992]])

# Reshaping Tensors

Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [21]:
x = torch.randn(4, 4)
print(x.size())

torch.Size([4, 4])


In [22]:
y = x.view(16)
print(y.size())

torch.Size([16])


In [23]:
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(z.size())

torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [24]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-2.4534])
-2.453388214111328


NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [25]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [26]:
print(type(a))

<class 'torch.Tensor'>


In [27]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [28]:
print(type(b))

<class 'numpy.ndarray'>


See how the numpy array changed in value.



Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [31]:
from_np = torch.from_numpy(b)
print(from_np)

tensor([1., 1., 1., 1., 1.])


# Tensors

In [32]:
import matplotlib.image as mpimg 
import matplotlib.pyplot as plt 


In [33]:
img = mpimg.imread('nn.png') 

In [34]:
type(img)

numpy.ndarray

In [35]:
img.shape

(720, 1280, 4)

In [36]:
img_to_np = torch.from_numpy(img)

In [37]:
img_to_np.shape

torch.Size([720, 1280, 4])